[2022-07-14 00:00:01,366] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-07-13T00:00:00+00:00 [queued]>
[2022-07-14 00:00:01,376] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: user_processing.create_table scheduled__2022-07-13T00:00:00+00:00 [queued]>
[2022-07-14 00:00:01,377] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 00:00:01,377] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-07-14 00:00:01,377] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-07-14 00:00:01,396] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_table> on 2022-07-13 00:00:00+00:00
[2022-07-14 00:00:01,400] {standard_task_runner.py:52} INFO - Started process 19160 to run task
[2022-07-14 00:00:01,405] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'create_table', 'scheduled__2022-07-13T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpyolbw1g9', '--error-file', '/tmp/tmp31d_g5rr']
[2022-07-14 00:00:01,407] {standard_task_runner.py:80} INFO - Job 26: Subtask create_table
[2022-07-14 00:00:01,483] {task_command.py:371} INFO - Running <TaskInstance: user_processing.create_table scheduled__2022-07-13T00:00:00+00:00 [running]> on host b0c7b58a654d
[2022-07-14 00:00:01,674] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-07-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-07-13T00:00:00+00:00
[2022-07-14 00:00:01,699] {base.py:68} INFO - Using connection ID 'postgres' for task execution.
[2022-07-14 00:00:01,705] {dbapi.py:231} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
                firstname TEXT NOT NULL,
                lastname TEXT NOT NULL,
                country TEXT NOT NULL,
                username TEXT NOT NULL,
                password TEXT NOT NULL,
                email TEXT NOT NULL
            );
            , parameters: None
[2022-07-14 00:00:01,709] {postgres.py:94} INFO - NOTICE:  relation "users" already exists, skipping

[2022-07-14 00:00:01,737] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20220713T000000, start_date=20220714T000001, end_date=20220714T000001
[2022-07-14 00:00:01,836] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-07-14 00:00:02,003] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
